serve:
  proxy:
    host: 0.0.0.0 # Cloud Run requirements
    port: 8080 
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories: # overwritten elsewhere

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # You could add some other headers, for example with data from the
        # session.
        # X-Some-Arbitrary-Data: "{{ print .Extra.some.arbitrary.data }}"
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455/
      jwks_url: file:///jwks.json

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  noop:
    enabled: true

  oauth2_client_credentials:
    enabled: true
    config:
      token_url: https://oauth2.googleapis.com/token
  #    required_scope:

  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://oauth2.googleapis.com/tokeninfo
#      scope_strategy: exact
#      required_scope:
#        - https://www.googleapis.com/auth/userinfo.email

  jwt:
    enabled: true
    config:
      jwks_urls:
        - https://www.googleapis.com/oauth2/v3/certs
#      scope_strategy: hierarchic
#      required_scope:
#        - email
      #target_audience:
      #  - https://my-service.com/api/users
      #  - https://my-service.com/api/devices
      trusted_issuers:
        - https://accounts.google.com
      allowed_algorithms:
        - RS256